### ISSUE TITLE
apm service goes into frequent restarts

### ISSUE THREAD

**Issue by Pratapud99** [elastic/apm-server#11380]
Please use the [discuss forum](https://discuss.elastic.co/c/apm) to ask questions. 
Hi, I'm running elk stack on version 7.17.9 and from some days i'm facing issue of apm-server service going into frequent restarts.
Not seeing any error in apm logs which could cause this issue.
Seeing this below error only in journalctl logs

apm-server: fatal error: concurrent map iteration and map write

**Comment by kruskall** [comment]
Hi @Pratapud99 :wave: 

There was a similar issue in the beats library which was fixed in 7.17.11: https://github.com/elastic/beats/issues/32467

Could you try to upgrade to 7.17.12 and try to reproduce the issue ?

**Comment by axw** [comment]
@Pratapud99 if after upgrading you're still having issues, please open a topic at https://discuss.elastic.co/c/observability/apm/58
