### ISSUE TITLE
[OpenTelemetry] Map OpenTelemetry `messaging.*` semantic conventions to Elastic Common Schema

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-server#5094]
Issue reported by https://github.com/gbanasiak on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3093

**Is your feature request related to a problem? Please describe.**

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/671 introduced translation of `http.*` and `db.*` semantic conventions into Elastic equivalent, i.e. `span.destination.*` fields. The missing bit are `messaging.*` [conventions ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md) which make service map presentation of services using components such as Kafka or RabbitMQ incomplete.

**Describe the solution you'd like**

Expand [existing translation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.24.0/exporter/elasticexporter/internal/translator/elastic/traces.go#L293-L349) to include `messaging.*` conventions.

**Describe alternatives you've considered**

The alternative would be to use semantic convention for which translation exists (e.g. `db.*`) while manually instrumenting messaging spans, but that's hacky.

**Comment by cyrille-leclerc** [comment]
@axw was it fixed in 7.14 or 7.15?

**Comment by axw** [comment]
@cyrille-leclerc https://github.com/elastic/apm-server/pull/5334 was merged into 7.14.

**Comment by tiny-dancer** [comment]
@axw  minor this is still appearing in the limitations documentation: https://www.elastic.co/guide/en/apm/guide/current/open-telemetry.html#open-telemetry-known-limitations

**Comment by axw** [comment]
@tiny-dancer thanks for the heads up. There's still an issue remaining, which I'll write up and link from the docs soon. The gist is that OTel doesn't provide enough information for us to always correctly classify an OTel span as an Elastic APM transaction/span.
